- hosts: terraform-ansible
  tasks:
  - name: create file
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>Esse bilhete eh verdade</h1>
  - name: create server
    shell: "nohup busybox httpd -f -p 8080 &"